# This is a basic workflow to help you get started with Actions

name: Bounty CI

on: issue_comment

jobs:
  commented_set:
    name: Set the bounty
    if: ${{ startsWith(github.event.comment.body, '/set_bounty') }}
    runs-on: ubuntu-latest
    container: 
      image: paravirtualtishu/mxpy:latest
      env:
        GITHUB_USER: ${{ github.event.comment.user.login }}
        GITHUB_ISSUE_ID: ${{ github.event.issue.id }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can check
      # the issuers.txt and hunters.txt files
      # - uses: actions/checkout@v3

      - name: Check comment is "/set_bounty bounty"
        uses: actions-ecosystem/action-regex-match@v2.0.2
        id: exact_match
        with:
          text: ${{ github.event.comment.body }}
          regex: '^\/set_bounty (\d+)$'
      
      - name: Uppercase username
        shell: bash
        run: |
          echo "$GITHUB_PEM_SECRET_KEY"
          echo "GITHUB_PEM_SECRET_KEY=${GITHUB_USER^^}_PEM_SECRET" >>${GITHUB_ENV}

      - name: Set bounty
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_ISSUE_BOUNTY: ${{ steps.exact_match.outputs.group1 }}
        if: ${{ steps.exact_match.outputs.match != '' && github.event.comment.user.login == github.event.issue.user.login }}
        run: |
          echo "The bounty: $GITHUB_ISSUE_BOUNTY"
          echo "${{ secrets[env.GITHUB_PEM_SECRET_KEY] }}" > key.pem
          issue_id_hex=$(echo -n $GITHUB_ISSUE_ID | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')
          user_hex=$(echo -n $GITHUB_USER | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')

          echo $issue_id_hex
          echo $user_hex

          mxpy --verbose contract call erd1qqqqqqqqqqqqqpgq6k3ujmztmpj4kz0660u237lwnvcc7tlqu5msppanh7 \
            --pem key.pem \
            --gas-limit=10000000 \
            --function="register_issue" \
            --chain D \
            --proxy="https://devnet-gateway.multiversx.com" \
            --recall-nonce \
            --send \
            --arguments 0x"$issue_id_hex" 0x"$user_hex" "$GITHUB_ISSUE_BOUNTY"000000000000000000

  commented_grant:
    name: Grant the bounty
    if: ${{ startsWith(github.event.comment.body, '/grant_bounty') }}
    runs-on: ubuntu-latest
    container: 
      image: paravirtualtishu/mxpy:latest
      env:
        GITHUB_USER: ${{ github.event.comment.user.login }}
        GITHUB_ISSUE_ID: ${{ github.event.issue.id }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can check
      # the issuers.txt and hunters.txt files
      # - uses: actions/checkout@v3

      - name: Check comment is "/grant_bounty @github_username"
        uses: actions-ecosystem/action-regex-match@v2.0.2
        id: exact_match
        with:
          text: ${{ github.event.comment.body }}
          regex: '^\/grant_bounty @(\w+)$'

      - name: Uppercase username
        shell: bash
        run: |
          echo "$GITHUB_PEM_SECRET_KEY"
          echo "GITHUB_PEM_SECRET_KEY=${GITHUB_USER^^}_PEM_SECRET" >>${GITHUB_ENV}

      - name: Grant bounty
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_HUNTER: ${{ steps.exact_match.outputs.group1 }}
        if: ${{ steps.exact_match.outputs.match != '' && github.event.comment.user.login == github.event.issue.user.login }}
        run: |
          echo "${{ secrets[env.GITHUB_PEM_SECRET_KEY] }}" > key.pem
          issue_id_hex=$(echo -n $GITHUB_ISSUE_ID | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')
          user_hex=$(echo -n $GITHUB_HUNTER | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')

          mxpy --verbose contract call erd1qqqqqqqqqqqqqpgq6k3ujmztmpj4kz0660u237lwnvcc7tlqu5msppanh7 \
            --pem key.pem \
            --gas-limit=10000000 \
            --function="claim_bounty" \
            --chain D \
            --proxy="https://devnet-gateway.multiversx.com" \
            --recall-nonce \
            --send \
            --arguments 0x"$issue_id_hex" 0x"$user_hex"

  claim_fund:
    name: Reclaim your fund
    if: ${{ startsWith(github.event.comment.body, '/claim_fund') }}
    runs-on: ubuntu-latest
    container: 
      image: paravirtualtishu/mxpy:latest
      env:
        GITHUB_USER: ${{ github.event.comment.user.login }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can check
      # the issuers.txt and hunters.txt files
      # - uses: actions/checkout@v3

      - name: Check comment is "/claim_fund"
        uses: actions-ecosystem/action-regex-match@v2.0.2
        id: exact_match
        with:
          text: ${{ github.event.comment.body }}
          regex: '^\/claim_fund$'

      - name: Uppercase username
        shell: bash
        run: |
          echo "$GITHUB_PEM_SECRET_KEY"
          echo "GITHUB_PEM_SECRET_KEY=${GITHUB_USER^^}_PEM_SECRET" >>${GITHUB_ENV}

      - name: Claim bounty fund back
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        if: ${{ steps.exact_match.outputs.match != '' && github.event.comment.user.login == github.event.issue.user.login }}
        run: |
          echo "${{ secrets[env.GITHUB_PEM_SECRET_KEY] }}" > key.pem
          user_hex=$(echo -n $GITHUB_USER | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')

          mxpy --verbose contract call erd1qqqqqqqqqqqqqpgq6k3ujmztmpj4kz0660u237lwnvcc7tlqu5msppanh7 \
            --pem key.pem \
            --gas-limit=10000000 \
            --function="claim_fund" \
            --chain D \
            --proxy="https://devnet-gateway.multiversx.com" \
            --recall-nonce \
            --send \
            --arguments 0x"$user_hex"